apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
  namespace: jenkins
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: mlops-dev-rg
spec:
  type: LoadBalancer
  loadBalancerIP: 52.234.153.72
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/component: jenkins-controller
